// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/core/services/audio_storage_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:repertoire_coach/core/services/r2_signer_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeR2UploadTarget_0 extends _i1.SmartFake
    implements _i2.R2UploadTarget {
  _FakeR2UploadTarget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [R2SignerClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockR2SignerClient extends _i1.Mock implements _i2.R2SignerClient {
  MockR2SignerClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getPlayUrl(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #getPlayUrl,
          [trackId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getPlayUrl,
            [trackId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i2.R2UploadTarget> getUploadUrl({
    required String? choirId,
    required String? trackId,
    required String? extension,
    required String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadUrl,
          [],
          {
            #choirId: choirId,
            #trackId: trackId,
            #extension: extension,
            #contentType: contentType,
          },
        ),
        returnValue: _i3.Future<_i2.R2UploadTarget>.value(_FakeR2UploadTarget_0(
          this,
          Invocation.method(
            #getUploadUrl,
            [],
            {
              #choirId: choirId,
              #trackId: trackId,
              #extension: extension,
              #contentType: contentType,
            },
          ),
        )),
      ) as _i3.Future<_i2.R2UploadTarget>);

  @override
  _i3.Future<void> deleteObject(
    String? storagePath,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteObject,
          [
            storagePath,
            trackId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
