// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/core/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/data/datasources/local/database.dart' as _i17;
import 'package:repertoire_coach/data/datasources/local/local_choir_data_source.dart'
    as _i2;
import 'package:repertoire_coach/data/datasources/local/local_concert_data_source.dart'
    as _i6;
import 'package:repertoire_coach/data/datasources/local/local_favorite_track_data_source.dart'
    as _i15;
import 'package:repertoire_coach/data/datasources/local/local_marker_data_source.dart'
    as _i12;
import 'package:repertoire_coach/data/datasources/local/local_song_data_source.dart'
    as _i8;
import 'package:repertoire_coach/data/datasources/local/local_track_data_source.dart'
    as _i10;
import 'package:repertoire_coach/data/datasources/remote/remote_choir_data_source.dart'
    as _i18;
import 'package:repertoire_coach/data/datasources/remote/remote_concert_data_source.dart'
    as _i19;
import 'package:repertoire_coach/data/datasources/remote/remote_favorite_track_data_source.dart'
    as _i23;
import 'package:repertoire_coach/data/datasources/remote/remote_marker_data_source.dart'
    as _i22;
import 'package:repertoire_coach/data/datasources/remote/remote_song_data_source.dart'
    as _i20;
import 'package:repertoire_coach/data/datasources/remote/remote_track_data_source.dart'
    as _i21;
import 'package:repertoire_coach/data/models/choir_member_model.dart' as _i5;
import 'package:repertoire_coach/data/models/choir_model.dart' as _i4;
import 'package:repertoire_coach/data/models/concert_model.dart' as _i7;
import 'package:repertoire_coach/data/models/favorite_track_model.dart' as _i16;
import 'package:repertoire_coach/data/models/marker_model.dart' as _i14;
import 'package:repertoire_coach/data/models/marker_set_model.dart' as _i13;
import 'package:repertoire_coach/data/models/song_model.dart' as _i9;
import 'package:repertoire_coach/data/models/track_model.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalChoirDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalChoirDataSource extends _i1.Mock
    implements _i2.LocalChoirDataSource {
  MockLocalChoirDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.ChoirModel>> watchChoirs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchChoirs,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.ChoirModel>>.empty(),
      ) as _i3.Stream<List<_i4.ChoirModel>>);

  @override
  _i3.Future<List<_i4.ChoirModel>> getChoirs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChoirs,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.ChoirModel>>.value(<_i4.ChoirModel>[]),
      ) as _i3.Future<List<_i4.ChoirModel>>);

  @override
  _i3.Future<_i4.ChoirModel?> getChoirById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getChoirById,
          [id],
        ),
        returnValue: _i3.Future<_i4.ChoirModel?>.value(),
      ) as _i3.Future<_i4.ChoirModel?>);

  @override
  _i3.Future<void> createChoir(
    _i4.ChoirModel? choir,
    String? creatorUserId, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChoir,
          [
            choir,
            creatorUserId,
          ],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateChoir(
    _i4.ChoirModel? choir, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChoir,
          [choir],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> upsertChoir(
    _i4.ChoirModel? choir, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertChoir,
          [choir],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertMember(
    _i5.ChoirMemberModel? member, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMember,
          [member],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteChoir(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChoir,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addMember(
    String? choirId,
    String? userId, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            choirId,
            userId,
          ],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> removeMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> getChoirMembers(String? choirId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChoirMembers,
          [choirId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOwner,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getMemberCount(String? choirId) => (super.noSuchMethod(
        Invocation.method(
          #getMemberCount,
          [choirId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.ChoirModel>> getUnsyncedChoirs() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedChoirs,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ChoirModel>>.value(<_i4.ChoirModel>[]),
      ) as _i3.Future<List<_i4.ChoirModel>>);

  @override
  _i3.Future<void> markChoirAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markChoirAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ChoirMemberModel>> getUnsyncedMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMembers,
          [],
        ),
        returnValue: _i3.Future<List<_i5.ChoirMemberModel>>.value(
            <_i5.ChoirMemberModel>[]),
      ) as _i3.Future<List<_i5.ChoirMemberModel>>);

  @override
  _i3.Future<void> markMemberAsSynced(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMemberAsSynced,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedChoirsNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedChoirsNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeletedChoirs() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeletedChoirs,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedMembersNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedMembersNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeletedMembers() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeletedMembers,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i4.ChoirModel>> getSyncedChoirs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedChoirs,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i4.ChoirModel>>.value(
            <String, _i4.ChoirModel>{}),
      ) as _i3.Future<Map<String, _i4.ChoirModel>>);

  @override
  _i3.Future<Map<String, _i5.ChoirMemberModel>> getSyncedMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedMembers,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i5.ChoirMemberModel>>.value(
            <String, _i5.ChoirMemberModel>{}),
      ) as _i3.Future<Map<String, _i5.ChoirMemberModel>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalConcertDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalConcertDataSource extends _i1.Mock
    implements _i6.LocalConcertDataSource {
  MockLocalConcertDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i7.ConcertModel>> watchConcerts() => (super.noSuchMethod(
        Invocation.method(
          #watchConcerts,
          [],
        ),
        returnValue: _i3.Stream<List<_i7.ConcertModel>>.empty(),
      ) as _i3.Stream<List<_i7.ConcertModel>>);

  @override
  _i3.Future<List<_i7.ConcertModel>> getConcerts() => (super.noSuchMethod(
        Invocation.method(
          #getConcerts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i7.ConcertModel>>.value(<_i7.ConcertModel>[]),
      ) as _i3.Future<List<_i7.ConcertModel>>);

  @override
  _i3.Future<_i7.ConcertModel?> getConcertById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcertById,
          [id],
        ),
        returnValue: _i3.Future<_i7.ConcertModel?>.value(),
      ) as _i3.Future<_i7.ConcertModel?>);

  @override
  _i3.Future<void> upsertConcert(
    _i7.ConcertModel? concert, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertConcert,
          [concert],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertConcert(
    _i7.ConcertModel? concert, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertConcert,
          [concert],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateConcert(
    _i7.ConcertModel? concert, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConcert,
          [concert],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteConcert(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConcert,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.ConcertModel>> getUnsyncedConcerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedConcerts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i7.ConcertModel>>.value(<_i7.ConcertModel>[]),
      ) as _i3.Future<List<_i7.ConcertModel>>);

  @override
  _i3.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteConcertsNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteConcertsNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i7.ConcertModel>> getSyncedConcerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedConcerts,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i7.ConcertModel>>.value(
            <String, _i7.ConcertModel>{}),
      ) as _i3.Future<Map<String, _i7.ConcertModel>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalSongDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalSongDataSource extends _i1.Mock
    implements _i8.LocalSongDataSource {
  MockLocalSongDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i9.SongModel>> watchSongsByConcert(String? concertId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSongsByConcert,
          [concertId],
        ),
        returnValue: _i3.Stream<List<_i9.SongModel>>.empty(),
      ) as _i3.Stream<List<_i9.SongModel>>);

  @override
  _i3.Future<List<_i9.SongModel>> getSongsByConcert(String? concertId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSongsByConcert,
          [concertId],
        ),
        returnValue: _i3.Future<List<_i9.SongModel>>.value(<_i9.SongModel>[]),
      ) as _i3.Future<List<_i9.SongModel>>);

  @override
  _i3.Future<_i9.SongModel?> getSongById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSongById,
          [id],
        ),
        returnValue: _i3.Future<_i9.SongModel?>.value(),
      ) as _i3.Future<_i9.SongModel?>);

  @override
  _i3.Future<void> upsertSong(
    _i9.SongModel? song, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertSong,
          [song],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSong(
    _i9.SongModel? song, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSong,
          [song],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateSong(
    _i9.SongModel? song, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSong,
          [song],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteSong(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSong,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.SongModel>> getUnsyncedSongs() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedSongs,
          [],
        ),
        returnValue: _i3.Future<List<_i9.SongModel>>.value(<_i9.SongModel>[]),
      ) as _i3.Future<List<_i9.SongModel>>);

  @override
  _i3.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSongsNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSongsNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i9.SongModel>> getSyncedSongs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedSongs,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i9.SongModel>>.value(
            <String, _i9.SongModel>{}),
      ) as _i3.Future<Map<String, _i9.SongModel>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalTrackDataSource extends _i1.Mock
    implements _i10.LocalTrackDataSource {
  MockLocalTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i11.TrackModel>> watchTracksBySong(String? songId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTracksBySong,
          [songId],
        ),
        returnValue: _i3.Stream<List<_i11.TrackModel>>.empty(),
      ) as _i3.Stream<List<_i11.TrackModel>>);

  @override
  _i3.Future<List<_i11.TrackModel>> getTracksBySong(String? songId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTracksBySong,
          [songId],
        ),
        returnValue:
            _i3.Future<List<_i11.TrackModel>>.value(<_i11.TrackModel>[]),
      ) as _i3.Future<List<_i11.TrackModel>>);

  @override
  _i3.Future<_i11.TrackModel?> getTrackById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTrackById,
          [id],
        ),
        returnValue: _i3.Future<_i11.TrackModel?>.value(),
      ) as _i3.Future<_i11.TrackModel?>);

  @override
  _i3.Future<void> upsertTrack(
    _i11.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertTrack(
    _i11.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateTrack(
    _i11.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteTrack(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrack,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteTracksNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteTracksNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i11.TrackModel>> getUnsyncedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedTracks,
          [],
        ),
        returnValue:
            _i3.Future<List<_i11.TrackModel>>.value(<_i11.TrackModel>[]),
      ) as _i3.Future<List<_i11.TrackModel>>);

  @override
  _i3.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i11.TrackModel>> getSyncedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedTracks,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i11.TrackModel>>.value(
            <String, _i11.TrackModel>{}),
      ) as _i3.Future<Map<String, _i11.TrackModel>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalMarkerDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalMarkerDataSource extends _i1.Mock
    implements _i12.LocalMarkerDataSource {
  MockLocalMarkerDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i13.MarkerSetModel>> getMarkerSetsByTrack(
    String? trackId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsByTrack,
          [trackId],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i13.MarkerSetModel>>.value(
            <_i13.MarkerSetModel>[]),
      ) as _i3.Future<List<_i13.MarkerSetModel>>);

  @override
  _i3.Stream<List<_i13.MarkerSetModel>> watchMarkerSetsByTrack(
    String? trackId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMarkerSetsByTrack,
          [trackId],
          {#userId: userId},
        ),
        returnValue: _i3.Stream<List<_i13.MarkerSetModel>>.empty(),
      ) as _i3.Stream<List<_i13.MarkerSetModel>>);

  @override
  _i3.Future<_i13.MarkerSetModel?> getMarkerSetById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetById,
          [id],
        ),
        returnValue: _i3.Future<_i13.MarkerSetModel?>.value(),
      ) as _i3.Future<_i13.MarkerSetModel?>);

  @override
  _i3.Future<void> upsertMarkerSet(
    _i13.MarkerSetModel? markerSet, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMarkerSet,
          [markerSet],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertMarkerSet(
    _i13.MarkerSetModel? markerSet, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMarkerSet,
          [markerSet],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateMarkerSet(
    _i13.MarkerSetModel? markerSet, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarkerSet,
          [markerSet],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteMarkerSet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarkerSet,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i13.MarkerSetModel>> getUnsyncedMarkerSets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMarkerSets,
          [],
        ),
        returnValue: _i3.Future<List<_i13.MarkerSetModel>>.value(
            <_i13.MarkerSetModel>[]),
      ) as _i3.Future<List<_i13.MarkerSetModel>>);

  @override
  _i3.Future<void> markMarkerSetAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMarkerSetAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteMarkerSetsNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteMarkerSetsNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeletedMarkerSets() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeletedMarkerSets,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i13.MarkerSetModel>> getSyncedMarkerSets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedMarkerSets,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i13.MarkerSetModel>>.value(
            <String, _i13.MarkerSetModel>{}),
      ) as _i3.Future<Map<String, _i13.MarkerSetModel>>);

  @override
  _i3.Future<List<_i14.MarkerModel>> getMarkersByMarkerSet(
          String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersByMarkerSet,
          [markerSetId],
        ),
        returnValue:
            _i3.Future<List<_i14.MarkerModel>>.value(<_i14.MarkerModel>[]),
      ) as _i3.Future<List<_i14.MarkerModel>>);

  @override
  _i3.Stream<List<_i14.MarkerModel>> watchMarkersByMarkerSet(
          String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMarkersByMarkerSet,
          [markerSetId],
        ),
        returnValue: _i3.Stream<List<_i14.MarkerModel>>.empty(),
      ) as _i3.Stream<List<_i14.MarkerModel>>);

  @override
  _i3.Future<_i14.MarkerModel?> getMarkerById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerById,
          [id],
        ),
        returnValue: _i3.Future<_i14.MarkerModel?>.value(),
      ) as _i3.Future<_i14.MarkerModel?>);

  @override
  _i3.Future<void> upsertMarker(
    _i14.MarkerModel? marker, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMarker,
          [marker],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertMarker(
    _i14.MarkerModel? marker, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMarker,
          [marker],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateMarker(
    _i14.MarkerModel? marker, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarker,
          [marker],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteMarker(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarker,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMarkersByMarkerSet(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMarkersByMarkerSet,
          [markerSetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> replaceMarkersByMarkerSet(
    String? markerSetId,
    List<_i14.MarkerModel>? markers, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceMarkersByMarkerSet,
          [
            markerSetId,
            markers,
          ],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i14.MarkerModel>> getUnsyncedMarkers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMarkers,
          [],
        ),
        returnValue:
            _i3.Future<List<_i14.MarkerModel>>.value(<_i14.MarkerModel>[]),
      ) as _i3.Future<List<_i14.MarkerModel>>);

  @override
  _i3.Future<void> hardDeleteMarkersNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteMarkersNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markMarkerAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMarkerAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeletedMarkers() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeletedMarkers,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i14.MarkerModel>> getSyncedMarkers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedMarkers,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i14.MarkerModel>>.value(
            <String, _i14.MarkerModel>{}),
      ) as _i3.Future<Map<String, _i14.MarkerModel>>);
}

/// A class which mocks [LocalFavoriteTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFavoriteTrackDataSource extends _i1.Mock
    implements _i15.LocalFavoriteTrackDataSource {
  MockLocalFavoriteTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i16.FavoriteTrackModel>> watchFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchFavorites,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i16.FavoriteTrackModel>>.empty(),
      ) as _i3.Stream<List<_i16.FavoriteTrackModel>>);

  @override
  _i3.Future<List<_i16.FavoriteTrackModel>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i16.FavoriteTrackModel>>.value(
            <_i16.FavoriteTrackModel>[]),
      ) as _i3.Future<List<_i16.FavoriteTrackModel>>);

  @override
  _i3.Future<bool> isFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addFavorite(
    String? userId,
    _i16.FavoriteTrackModel? favorite, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            userId,
            favorite,
          ],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getFavoriteCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clearAllForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAllForUser,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i16.FavoriteTrackModel>> getUnsyncedFavorites(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i16.FavoriteTrackModel>>.value(
            <_i16.FavoriteTrackModel>[]),
      ) as _i3.Future<List<_i16.FavoriteTrackModel>>);

  @override
  _i3.Future<List<_i17.FavoriteTrack>> getUnsyncedFavoriteRecords(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFavoriteRecords,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i17.FavoriteTrack>>.value(<_i17.FavoriteTrack>[]),
      ) as _i3.Future<List<_i17.FavoriteTrack>>);

  @override
  _i3.Future<void> markAsSynced(
    List<String>? trackIds,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            trackIds,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertFavoriteRecord({
    required String? userId,
    required String? trackId,
    required String? songId,
    required DateTime? addedAt,
    bool? markForSync = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertFavoriteRecord,
          [],
          {
            #userId: userId,
            #trackId: trackId,
            #songId: songId,
            #addedAt: addedAt,
            #markForSync: markForSync,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedNotIn(
    String? userId,
    Set<String>? keepTrackIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedNotIn,
          [
            userId,
            keepTrackIds,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i16.FavoriteTrackModel>> getSyncedFavorites(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedFavorites,
          [userId],
        ),
        returnValue: _i3.Future<Map<String, _i16.FavoriteTrackModel>>.value(
            <String, _i16.FavoriteTrackModel>{}),
      ) as _i3.Future<Map<String, _i16.FavoriteTrackModel>>);
}

/// A class which mocks [RemoteChoirDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteChoirDataSource extends _i1.Mock
    implements _i18.RemoteChoirDataSource {
  MockRemoteChoirDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ChoirModel>> getChoirs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChoirs,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.ChoirModel>>.value(<_i4.ChoirModel>[]),
      ) as _i3.Future<List<_i4.ChoirModel>>);

  @override
  _i3.Future<_i4.ChoirModel?> getChoirById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getChoirById,
          [id],
        ),
        returnValue: _i3.Future<_i4.ChoirModel?>.value(),
      ) as _i3.Future<_i4.ChoirModel?>);

  @override
  _i3.Future<void> createChoir(
    _i4.ChoirModel? choir,
    String? creatorUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChoir,
          [
            choir,
            creatorUserId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateChoir(_i4.ChoirModel? choir) => (super.noSuchMethod(
        Invocation.method(
          #updateChoir,
          [choir],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteChoir(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChoir,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getChoirMembers(String? choirId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChoirMembers,
          [choirId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOwner,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getMemberCount(String? choirId) => (super.noSuchMethod(
        Invocation.method(
          #getMemberCount,
          [choirId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.ChoirMemberModel>> getChoirMembersForUser(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChoirMembersForUser,
          [userId],
        ),
        returnValue: _i3.Future<List<_i5.ChoirMemberModel>>.value(
            <_i5.ChoirMemberModel>[]),
      ) as _i3.Future<List<_i5.ChoirMemberModel>>);
}

/// A class which mocks [RemoteConcertDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConcertDataSource extends _i1.Mock
    implements _i19.RemoteConcertDataSource {
  MockRemoteConcertDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.ConcertModel>> getConcerts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcerts,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i7.ConcertModel>>.value(<_i7.ConcertModel>[]),
      ) as _i3.Future<List<_i7.ConcertModel>>);

  @override
  _i3.Future<_i7.ConcertModel?> getConcertById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcertById,
          [id],
        ),
        returnValue: _i3.Future<_i7.ConcertModel?>.value(),
      ) as _i3.Future<_i7.ConcertModel?>);

  @override
  _i3.Future<void> createConcert(_i7.ConcertModel? concert) =>
      (super.noSuchMethod(
        Invocation.method(
          #createConcert,
          [concert],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateConcert(_i7.ConcertModel? concert) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConcert,
          [concert],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteConcert(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConcert,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RemoteSongDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteSongDataSource extends _i1.Mock
    implements _i20.RemoteSongDataSource {
  MockRemoteSongDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i9.SongModel>> getSongsByConcertId(String? concertId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSongsByConcertId,
          [concertId],
        ),
        returnValue: _i3.Future<List<_i9.SongModel>>.value(<_i9.SongModel>[]),
      ) as _i3.Future<List<_i9.SongModel>>);

  @override
  _i3.Future<_i9.SongModel?> getSongById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSongById,
          [id],
        ),
        returnValue: _i3.Future<_i9.SongModel?>.value(),
      ) as _i3.Future<_i9.SongModel?>);

  @override
  _i3.Future<void> createSong(_i9.SongModel? song) => (super.noSuchMethod(
        Invocation.method(
          #createSong,
          [song],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSong(_i9.SongModel? song) => (super.noSuchMethod(
        Invocation.method(
          #updateSong,
          [song],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSong(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSong,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.SongModel>> getSongsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSongsForUser,
          [userId],
        ),
        returnValue: _i3.Future<List<_i9.SongModel>>.value(<_i9.SongModel>[]),
      ) as _i3.Future<List<_i9.SongModel>>);
}

/// A class which mocks [RemoteTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteTrackDataSource extends _i1.Mock
    implements _i21.RemoteTrackDataSource {
  MockRemoteTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.TrackModel>> getTracksBySongId(String? songId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTracksBySongId,
          [songId],
        ),
        returnValue:
            _i3.Future<List<_i11.TrackModel>>.value(<_i11.TrackModel>[]),
      ) as _i3.Future<List<_i11.TrackModel>>);

  @override
  _i3.Future<_i11.TrackModel?> getTrackById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTrackById,
          [id],
        ),
        returnValue: _i3.Future<_i11.TrackModel?>.value(),
      ) as _i3.Future<_i11.TrackModel?>);

  @override
  _i3.Future<void> createTrack(_i11.TrackModel? track) => (super.noSuchMethod(
        Invocation.method(
          #createTrack,
          [track],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTrack(_i11.TrackModel? track) => (super.noSuchMethod(
        Invocation.method(
          #updateTrack,
          [track],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTrack(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrack,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i11.TrackModel>> getTracksForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTracksForUser,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i11.TrackModel>>.value(<_i11.TrackModel>[]),
      ) as _i3.Future<List<_i11.TrackModel>>);
}

/// A class which mocks [RemoteMarkerDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteMarkerDataSource extends _i1.Mock
    implements _i22.RemoteMarkerDataSource {
  MockRemoteMarkerDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i13.MarkerSetModel>> getMarkerSetsByTrackId(
    String? trackId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsByTrackId,
          [
            trackId,
            userId,
          ],
        ),
        returnValue: _i3.Future<List<_i13.MarkerSetModel>>.value(
            <_i13.MarkerSetModel>[]),
      ) as _i3.Future<List<_i13.MarkerSetModel>>);

  @override
  _i3.Future<_i13.MarkerSetModel?> getMarkerSetById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetById,
          [id],
        ),
        returnValue: _i3.Future<_i13.MarkerSetModel?>.value(),
      ) as _i3.Future<_i13.MarkerSetModel?>);

  @override
  _i3.Future<void> createMarkerSet(_i13.MarkerSetModel? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMarkerSet,
          [markerSet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMarkerSet(_i13.MarkerSetModel? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarkerSet,
          [markerSet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMarkerSet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarkerSet,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i14.MarkerModel>> getMarkersBySetId(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersBySetId,
          [markerSetId],
        ),
        returnValue:
            _i3.Future<List<_i14.MarkerModel>>.value(<_i14.MarkerModel>[]),
      ) as _i3.Future<List<_i14.MarkerModel>>);

  @override
  _i3.Future<_i14.MarkerModel?> getMarkerById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerById,
          [id],
        ),
        returnValue: _i3.Future<_i14.MarkerModel?>.value(),
      ) as _i3.Future<_i14.MarkerModel?>);

  @override
  _i3.Future<void> createMarker(_i14.MarkerModel? marker) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMarker,
          [marker],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMarker(_i14.MarkerModel? marker) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarker,
          [marker],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMarker(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarker,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMarkersBySetId(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMarkersBySetId,
          [markerSetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i13.MarkerSetModel>> getMarkerSetsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsForUser,
          [userId],
        ),
        returnValue: _i3.Future<List<_i13.MarkerSetModel>>.value(
            <_i13.MarkerSetModel>[]),
      ) as _i3.Future<List<_i13.MarkerSetModel>>);

  @override
  _i3.Future<List<_i14.MarkerModel>> getMarkersForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersForUser,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i14.MarkerModel>>.value(<_i14.MarkerModel>[]),
      ) as _i3.Future<List<_i14.MarkerModel>>);
}

/// A class which mocks [RemoteFavoriteTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteFavoriteTrackDataSource extends _i1.Mock
    implements _i23.RemoteFavoriteTrackDataSource {
  MockRemoteFavoriteTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i16.FavoriteTrackModel>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i16.FavoriteTrackModel>>.value(
            <_i16.FavoriteTrackModel>[]),
      ) as _i3.Future<List<_i16.FavoriteTrackModel>>);

  @override
  _i3.Future<bool> isFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addFavorite(
    String? userId,
    String? trackId,
    String? songId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            userId,
            trackId,
            songId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<({DateTime addedAt, String songId, String trackId})>>
      getFavoritesForSync(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getFavoritesForSync,
              [userId],
            ),
            returnValue: _i3.Future<
                    List<
                        ({
                          DateTime addedAt,
                          String songId,
                          String trackId
                        })>>.value(
                <({DateTime addedAt, String songId, String trackId})>[]),
          ) as _i3.Future<
              List<({DateTime addedAt, String songId, String trackId})>>);

  @override
  _i3.Future<int> getFavoriteCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
