// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/data/repositories/favorite_track_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/data/datasources/local/database.dart' as _i5;
import 'package:repertoire_coach/data/datasources/local/local_favorite_track_data_source.dart'
    as _i2;
import 'package:repertoire_coach/data/datasources/local/local_track_data_source.dart'
    as _i6;
import 'package:repertoire_coach/data/models/favorite_track_model.dart' as _i4;
import 'package:repertoire_coach/data/models/track_model.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalFavoriteTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFavoriteTrackDataSource extends _i1.Mock
    implements _i2.LocalFavoriteTrackDataSource {
  MockLocalFavoriteTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.FavoriteTrackModel>> watchFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchFavorites,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.FavoriteTrackModel>>.empty(),
      ) as _i3.Stream<List<_i4.FavoriteTrackModel>>);

  @override
  _i3.Future<List<_i4.FavoriteTrackModel>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.FavoriteTrackModel>>.value(
            <_i4.FavoriteTrackModel>[]),
      ) as _i3.Future<List<_i4.FavoriteTrackModel>>);

  @override
  _i3.Future<bool> isFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addFavorite(
    String? userId,
    _i4.FavoriteTrackModel? favorite, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            userId,
            favorite,
          ],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getFavoriteCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clearAllForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAllForUser,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.FavoriteTrackModel>> getUnsyncedFavorites(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.FavoriteTrackModel>>.value(
            <_i4.FavoriteTrackModel>[]),
      ) as _i3.Future<List<_i4.FavoriteTrackModel>>);

  @override
  _i3.Future<List<_i5.FavoriteTrack>> getUnsyncedFavoriteRecords(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFavoriteRecords,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i5.FavoriteTrack>>.value(<_i5.FavoriteTrack>[]),
      ) as _i3.Future<List<_i5.FavoriteTrack>>);

  @override
  _i3.Future<void> markAsSynced(
    List<String>? trackIds,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            trackIds,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertFavoriteRecord({
    required String? userId,
    required String? trackId,
    required String? songId,
    required DateTime? addedAt,
    bool? markForSync = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertFavoriteRecord,
          [],
          {
            #userId: userId,
            #trackId: trackId,
            #songId: songId,
            #addedAt: addedAt,
            #markForSync: markForSync,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedNotIn(
    String? userId,
    Set<String>? keepTrackIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedNotIn,
          [
            userId,
            keepTrackIds,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i4.FavoriteTrackModel>> getSyncedFavorites(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedFavorites,
          [userId],
        ),
        returnValue: _i3.Future<Map<String, _i4.FavoriteTrackModel>>.value(
            <String, _i4.FavoriteTrackModel>{}),
      ) as _i3.Future<Map<String, _i4.FavoriteTrackModel>>);
}

/// A class which mocks [LocalTrackDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalTrackDataSource extends _i1.Mock
    implements _i6.LocalTrackDataSource {
  MockLocalTrackDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i7.TrackModel>> watchTracksBySong(String? songId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTracksBySong,
          [songId],
        ),
        returnValue: _i3.Stream<List<_i7.TrackModel>>.empty(),
      ) as _i3.Stream<List<_i7.TrackModel>>);

  @override
  _i3.Future<List<_i7.TrackModel>> getTracksBySong(String? songId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTracksBySong,
          [songId],
        ),
        returnValue: _i3.Future<List<_i7.TrackModel>>.value(<_i7.TrackModel>[]),
      ) as _i3.Future<List<_i7.TrackModel>>);

  @override
  _i3.Future<_i7.TrackModel?> getTrackById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTrackById,
          [id],
        ),
        returnValue: _i3.Future<_i7.TrackModel?>.value(),
      ) as _i3.Future<_i7.TrackModel?>);

  @override
  _i3.Future<void> upsertTrack(
    _i7.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertTrack(
    _i7.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateTrack(
    _i7.TrackModel? track, {
    bool? markForSync = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrack,
          [track],
          {#markForSync: markForSync},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteTrack(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrack,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteTracksNotIn(Set<String>? keepIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteTracksNotIn,
          [keepIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.TrackModel>> getUnsyncedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedTracks,
          [],
        ),
        returnValue: _i3.Future<List<_i7.TrackModel>>.value(<_i7.TrackModel>[]),
      ) as _i3.Future<List<_i7.TrackModel>>);

  @override
  _i3.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteSyncedDeleted() => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteSyncedDeleted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i7.TrackModel>> getSyncedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedTracks,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i7.TrackModel>>.value(
            <String, _i7.TrackModel>{}),
      ) as _i3.Future<Map<String, _i7.TrackModel>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
