// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/data/repositories/marker_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/core/services/supabase_service.dart' as _i7;
import 'package:repertoire_coach/data/datasources/remote/remote_marker_data_source.dart'
    as _i3;
import 'package:repertoire_coach/data/models/marker_model.dart' as _i6;
import 'package:repertoire_coach/data/models/marker_set_model.dart' as _i5;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteMarkerDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteMarkerDataSource extends _i1.Mock
    implements _i3.RemoteMarkerDataSource {
  MockRemoteMarkerDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MarkerSetModel>> getMarkerSetsByTrackId(
    String? trackId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsByTrackId,
          [
            trackId,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<List<_i5.MarkerSetModel>>.value(<_i5.MarkerSetModel>[]),
      ) as _i4.Future<List<_i5.MarkerSetModel>>);

  @override
  _i4.Future<_i5.MarkerSetModel?> getMarkerSetById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetById,
          [id],
        ),
        returnValue: _i4.Future<_i5.MarkerSetModel?>.value(),
      ) as _i4.Future<_i5.MarkerSetModel?>);

  @override
  _i4.Future<void> createMarkerSet(_i5.MarkerSetModel? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMarkerSet,
          [markerSet],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMarkerSet(_i5.MarkerSetModel? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarkerSet,
          [markerSet],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMarkerSet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarkerSet,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.MarkerModel>> getMarkersBySetId(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersBySetId,
          [markerSetId],
        ),
        returnValue:
            _i4.Future<List<_i6.MarkerModel>>.value(<_i6.MarkerModel>[]),
      ) as _i4.Future<List<_i6.MarkerModel>>);

  @override
  _i4.Future<_i6.MarkerModel?> getMarkerById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMarkerById,
          [id],
        ),
        returnValue: _i4.Future<_i6.MarkerModel?>.value(),
      ) as _i4.Future<_i6.MarkerModel?>);

  @override
  _i4.Future<void> createMarker(_i6.MarkerModel? marker) => (super.noSuchMethod(
        Invocation.method(
          #createMarker,
          [marker],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMarker(_i6.MarkerModel? marker) => (super.noSuchMethod(
        Invocation.method(
          #updateMarker,
          [marker],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMarker(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarker,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMarkersBySetId(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMarkersBySetId,
          [markerSetId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.MarkerSetModel>> getMarkerSetsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsForUser,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i5.MarkerSetModel>>.value(<_i5.MarkerSetModel>[]),
      ) as _i4.Future<List<_i5.MarkerSetModel>>);

  @override
  _i4.Future<List<_i6.MarkerModel>> getMarkersForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersForUser,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i6.MarkerModel>>.value(<_i6.MarkerModel>[]),
      ) as _i4.Future<List<_i6.MarkerModel>>);
}

/// A class which mocks [SupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseService extends _i1.Mock implements _i7.SupabaseService {
  MockSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i2.AuthState>.empty(),
      ) as _i4.Stream<_i2.AuthState>);
}
