// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/screens/choir_members_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:repertoire_coach/domain/entities/choir.dart' as _i4;
import 'package:repertoire_coach/domain/repositories/choir_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChoirRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChoirRepository extends _i1.Mock implements _i2.ChoirRepository {
  MockChoirRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Choir>> getChoirs(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getChoirs,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.Choir>>.value(<_i4.Choir>[]),
      ) as _i3.Future<List<_i4.Choir>>);

  @override
  _i3.Future<_i4.Choir?> getChoirById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getChoirById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Choir?>.value(),
      ) as _i3.Future<_i4.Choir?>);

  @override
  _i3.Future<String> createChoir(
    String? name,
    String? ownerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChoir,
          [
            name,
            ownerId,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createChoir,
            [
              name,
              ownerId,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateChoir(_i4.Choir? choir) => (super.noSuchMethod(
        Invocation.method(
          #updateChoir,
          [choir],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteChoir(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChoir,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> removeMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> getMembers(String? choirId) => (super.noSuchMethod(
        Invocation.method(
          #getMembers,
          [choirId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isMember(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMember,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(
    String? choirId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOwner,
          [
            choirId,
            userId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getMemberCount(String? choirId) => (super.noSuchMethod(
        Invocation.method(
          #getMemberCount,
          [choirId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
