// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/screens/favorite_tracks_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/favorite_track.dart' as _i4;
import 'package:repertoire_coach/domain/repositories/favorite_track_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoriteTrackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteTrackRepository extends _i1.Mock
    implements _i2.FavoriteTrackRepository {
  MockFavoriteTrackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteTrack>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i4.FavoriteTrack>>.value(<_i4.FavoriteTrack>[]),
      ) as _i3.Future<List<_i4.FavoriteTrack>>);

  @override
  _i3.Future<bool> isFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addFavorite(
    String? userId,
    String? trackId,
    String? songId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            userId,
            trackId,
            songId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getFavoriteCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
