// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/screens/marker_sync/time_sync_step_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/marker.dart' as _i5;
import 'package:repertoire_coach/domain/entities/marker_set.dart' as _i4;
import 'package:repertoire_coach/domain/repositories/marker_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MarkerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkerRepository extends _i1.Mock implements _i2.MarkerRepository {
  MockMarkerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MarkerSet>> getMarkerSetsByTrack(
    String? trackId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetsByTrack,
          [trackId],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i4.MarkerSet>>.value(<_i4.MarkerSet>[]),
      ) as _i3.Future<List<_i4.MarkerSet>>);

  @override
  _i3.Future<_i4.MarkerSet?> getMarkerSetById(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerSetById,
          [markerSetId],
        ),
        returnValue: _i3.Future<_i4.MarkerSet?>.value(),
      ) as _i3.Future<_i4.MarkerSet?>);

  @override
  _i3.Future<void> createMarkerSet(_i4.MarkerSet? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMarkerSet,
          [markerSet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateMarkerSet(_i4.MarkerSet? markerSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarkerSet,
          [markerSet],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteMarkerSet(String? markerSetId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarkerSet,
          [markerSetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Marker>> getMarkersByMarkerSet(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkersByMarkerSet,
          [markerSetId],
        ),
        returnValue: _i3.Future<List<_i5.Marker>>.value(<_i5.Marker>[]),
      ) as _i3.Future<List<_i5.Marker>>);

  @override
  _i3.Future<_i5.Marker?> getMarkerById(String? markerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkerById,
          [markerId],
        ),
        returnValue: _i3.Future<_i5.Marker?>.value(),
      ) as _i3.Future<_i5.Marker?>);

  @override
  _i3.Future<void> createMarker(_i5.Marker? marker) => (super.noSuchMethod(
        Invocation.method(
          #createMarker,
          [marker],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateMarker(_i5.Marker? marker) => (super.noSuchMethod(
        Invocation.method(
          #updateMarker,
          [marker],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteMarker(String? markerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMarker,
          [markerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMarkersByMarkerSet(String? markerSetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMarkersByMarkerSet,
          [markerSetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
