// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:mockito/mockito.dart' as i1;
import 'package:repertoire_coach/domain/entities/playback_info.dart' as i2;
import 'package:repertoire_coach/domain/entities/track.dart' as i5;
import 'package:repertoire_coach/domain/repositories/audio_player_repository.dart'
    as i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AudioPlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerRepository extends i1.Mock
    implements i3.AudioPlayerRepository {
  MockAudioPlayerRepository() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Stream<i2.PlaybackInfo> get playbackStream =>
      (super.noSuchMethod(Invocation.getter(#playbackStream),
              returnValue: i4.Stream<i2.PlaybackInfo>.empty())
          as i4.Stream<i2.PlaybackInfo>);
  @override
  i2.PlaybackInfo get currentPlayback =>
      (super.noSuchMethod(Invocation.getter(#currentPlayback),
          returnValue: i2.PlaybackInfo.idle()) as i2.PlaybackInfo);
  @override
  i4.Future<void> playTrack(i5.Track? track, {Duration? startPosition}) =>
      (super.noSuchMethod(
          Invocation.method(
              #playTrack, [track], {#startPosition: startPosition}),
          returnValue: i4.Future<void>.value(),
          returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<void> resume() =>
      (super.noSuchMethod(Invocation.method(#resume, []),
          returnValue: i4.Future<void>.value(),
          returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<void> pause() => (super.noSuchMethod(Invocation.method(#pause, []),
      returnValue: i4.Future<void>.value(),
      returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<void> stop() => (super.noSuchMethod(Invocation.method(#stop, []),
      returnValue: i4.Future<void>.value(),
      returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<Duration> seek(Duration? position) =>
      (super.noSuchMethod(Invocation.method(#seek, [position]),
          returnValue: i4.Future<Duration>.value(Duration.zero)) as i4.Future<Duration>);
  @override
  i4.Future<void> savePlaybackPosition() =>
      (super.noSuchMethod(Invocation.method(#savePlaybackPosition, []),
          returnValue: i4.Future<void>.value(),
          returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<Duration> loadPlaybackPosition(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#loadPlaybackPosition, [trackId]),
          returnValue: i4.Future<Duration>.value(Duration.zero)) as i4.Future<Duration>);
  @override
  i4.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: i4.Future<void>.value(),
          returnValueForMissingStub: i4.Future<void>.value()) as i4.Future<void>);
}