// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/choir.dart' as _i5;
import 'package:repertoire_coach/domain/repositories/choir_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFuture_0<T> extends _i1.Fake implements _i4.Future<T> {}

/// A class which mocks [ChoirRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChoirRepository extends _i1.Mock implements _i3.ChoirRepository {
  MockChoirRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Choir>> getChoirs(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getChoirs, [userId]),
              returnValue: Future.value(<_i5.Choir>[]))
          as _i4.Future<List<_i5.Choir>>);
  @override
  _i4.Future<_i5.Choir?> getChoirById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getChoirById, [id]),
              returnValue: Future.value(_i5.Choir(id: '', name: '', ownerId: '', createdAt: DateTime.now())))
          as _i4.Future<_i5.Choir?>);
  @override
  _i4.Future<String> createChoir(String? name, String? ownerId) =>
      (super.noSuchMethod(Invocation.method(#createChoir, [name, ownerId]),
          returnValue: Future.value('')) as _i4.Future<String>);
  @override
  _i4.Future<void> updateChoir(_i5.Choir? choir) =>
      (super.noSuchMethod(Invocation.method(#updateChoir, [choir]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteChoir(String? id) =>
      (super.noSuchMethod(Invocation.method(#deleteChoir, [id]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> addMember(String? choirId, String? userId) =>
      (super.noSuchMethod(Invocation.method(#addMember, [choirId, userId]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<bool> removeMember(String? choirId, String? userId) =>
      (super.noSuchMethod(Invocation.method(#removeMember, [choirId, userId]),
          returnValue: Future.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<List<String>> getMembers(String? choirId) =>
      (super.noSuchMethod(Invocation.method(#getMembers, [choirId]),
          returnValue: Future.value(<String>[])) as _i4.Future<List<String>>);
  @override
  _i4.Future<bool> isMember(String? choirId, String? userId) =>
      (super.noSuchMethod(Invocation.method(#isMember, [choirId, userId]),
          returnValue: Future.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<bool> isOwner(String? choirId, String? userId) =>
      (super.noSuchMethod(Invocation.method(#isOwner, [choirId, userId]),
          returnValue: Future.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<int> getMemberCount(String? choirId) =>
      (super.noSuchMethod(Invocation.method(#getMemberCount, [choirId]),
          returnValue: Future.value(0)) as _i4.Future<int>);
}
