// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:mockito/mockito.dart' as i1;
import 'package:repertoire_coach/domain/entities/concert.dart' as i5;
import 'package:repertoire_coach/domain/repositories/concert_repository.dart'
    as i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ConcertRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConcertRepository extends i1.Mock implements i3.ConcertRepository {
  MockConcertRepository() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<List<i5.Concert>> getConcerts() =>
      (super.noSuchMethod(Invocation.method(#getConcerts, []),
              returnValue: i4.Future.value(<i5.Concert>[]))
          as i4.Future<List<i5.Concert>>);
  @override
  i4.Future<List<i5.Concert>> getConcertsByChoir(String? choirId) =>
      (super.noSuchMethod(Invocation.method(#getConcertsByChoir, [choirId]),
              returnValue: i4.Future.value(<i5.Concert>[]))
          as i4.Future<List<i5.Concert>>);
  @override
  i4.Future<i5.Concert?> getConcertById(String? concertId) =>
      (super.noSuchMethod(Invocation.method(#getConcertById, [concertId]),
              returnValue: i4.Future.value(i5.Concert(id: '', name: '', choirId: '', choirName: '', concertDate: DateTime.now(), createdAt: DateTime.now())))
          as i4.Future<i5.Concert?>);
  @override
  i4.Future<void> createConcert(i5.Concert? concert) =>
      (super.noSuchMethod(Invocation.method(#createConcert, [concert]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
  @override
  i4.Future<bool> updateConcert(i5.Concert? concert) =>
      (super.noSuchMethod(Invocation.method(#updateConcert, [concert]),
          returnValue: i4.Future.value(false)) as i4.Future<bool>);
  @override
  i4.Future<void> deleteConcert(String? concertId) =>
      (super.noSuchMethod(Invocation.method(#deleteConcert, [concertId]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
}
