// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/providers/favorite_track_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/favorite_track.dart' as _i5;
import 'package:repertoire_coach/domain/entities/loop_range.dart' as _i8;
import 'package:repertoire_coach/domain/entities/playback_info.dart' as _i2;
import 'package:repertoire_coach/domain/entities/track.dart' as _i7;
import 'package:repertoire_coach/domain/repositories/audio_player_repository.dart'
    as _i6;
import 'package:repertoire_coach/domain/repositories/favorite_track_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlaybackInfo_0 extends _i1.SmartFake implements _i2.PlaybackInfo {
  _FakePlaybackInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoriteTrackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteTrackRepository extends _i1.Mock
    implements _i3.FavoriteTrackRepository {
  MockFavoriteTrackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.FavoriteTrack>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i5.FavoriteTrack>>.value(<_i5.FavoriteTrack>[]),
      ) as _i4.Future<List<_i5.FavoriteTrack>>);

  @override
  _i4.Future<bool> isFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> addFavorite(
    String? userId,
    String? trackId,
    String? songId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            userId,
            trackId,
            songId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(
    String? userId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            userId,
            trackId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getFavoriteCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [AudioPlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerRepository extends _i1.Mock
    implements _i6.AudioPlayerRepository {
  MockAudioPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.PlaybackInfo> get playbackStream => (super.noSuchMethod(
        Invocation.getter(#playbackStream),
        returnValue: _i4.Stream<_i2.PlaybackInfo>.empty(),
      ) as _i4.Stream<_i2.PlaybackInfo>);

  @override
  _i2.PlaybackInfo get currentPlayback => (super.noSuchMethod(
        Invocation.getter(#currentPlayback),
        returnValue: _FakePlaybackInfo_0(
          this,
          Invocation.getter(#currentPlayback),
        ),
      ) as _i2.PlaybackInfo);

  @override
  bool get isLooping => (super.noSuchMethod(
        Invocation.getter(#isLooping),
        returnValue: false,
      ) as bool);

  @override
  bool get isRangeLooping => (super.noSuchMethod(
        Invocation.getter(#isRangeLooping),
        returnValue: false,
      ) as bool);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> playTrack(
    _i7.Track? track, {
    String? audioUrl,
    String? songName,
    String? albumName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrack,
          [track],
          {
            #audioUrl: audioUrl,
            #songName: songName,
            #albumName: albumName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> prepareTrack(
    _i7.Track? track, {
    String? audioUrl,
    String? songName,
    String? albumName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareTrack,
          [track],
          {
            #audioUrl: audioUrl,
            #songName: songName,
            #albumName: albumName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Duration> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i4.Future<Duration>.value(_FakeDuration_1(
          this,
          Invocation.method(
            #seek,
            [position],
          ),
        )),
      ) as _i4.Future<Duration>);

  @override
  _i4.Future<void> setLoopMode(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLoopRange(_i8.LoopRange? loopRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLoopRange,
          [loopRange],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void notifyFavouritesChanged() => super.noSuchMethod(
        Invocation.method(
          #notifyFavouritesChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
