// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as i3;
import 'dart:typed_data' as i6;

import 'package:file_picker/file_picker.dart' as i2;
import 'package:mockito/mockito.dart' as i1;
import 'package:repertoire_coach/data/services/file_storage_service.dart'
    as i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FileStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileStorageService extends i1.Mock
    implements i5.FileStorageService {
  MockFileStorageService() {
    i1.throwOnMissingStub(this);
  }

  @override
  i3.Future<String> importAudioFile(String? sourcePath) =>
      (super.noSuchMethod(Invocation.method(#importAudioFile, [sourcePath]),
          returnValue: i3.Future<String>.value('')) as i3.Future<String>);
  @override
  i3.Future<bool> deleteAudioFile(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#deleteAudioFile, [filePath]),
          returnValue: i3.Future<bool>.value(false)) as i3.Future<bool>);
  @override
  i3.Future<bool> fileExists(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#fileExists, [filePath]),
          returnValue: i3.Future<bool>.value(false)) as i3.Future<bool>);
  @override
  i3.Future<int> getTotalStorageUsed() =>
      (super.noSuchMethod(Invocation.method(#getTotalStorageUsed, []),
          returnValue: i3.Future<int>.value(0)) as i3.Future<int>);
  @override
  i3.Future<int> clearAllAudioFiles() =>
      (super.noSuchMethod(Invocation.method(#clearAllAudioFiles, []),
          returnValue: i3.Future<int>.value(0)) as i3.Future<int>);
}

/// A class which mocks [FilePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePicker extends i1.Mock implements i2.FilePicker {
  MockFilePicker() {
    i1.throwOnMissingStub(this);
  }

  @override
  i3.Future<i2.FilePickerResult?> pickFiles(
          {String? dialogTitle,
          String? initialDirectory,
          i2.FileType? type,
          List<String>? allowedExtensions,
          dynamic onFileLoading,
          bool? allowMultiple,
          bool? withData,
          bool? withReadStream,
          bool? lockParentWindow,
          bool? allowCompression,
          bool? readSequential,
          String? restorationId,
          int? compressionQuality}) =>
      (super.noSuchMethod(
              Invocation.method(#pickFiles, [], {
                #dialogTitle: dialogTitle,
                #initialDirectory: initialDirectory,
                #type: type,
                #allowedExtensions: allowedExtensions,
                #onFileLoading: onFileLoading,
                #allowMultiple: allowMultiple,
                #withData: withData,
                #withReadStream: withReadStream,
                #lockParentWindow: lockParentWindow,
                #allowCompression: allowCompression,
                #readSequential: readSequential,
                #restorationId: restorationId,
                #compressionQuality: compressionQuality
              }),
              returnValue: i3.Future<i2.FilePickerResult?>.value(null))
          as i3.Future<i2.FilePickerResult?>);
  @override
  i3.Future<String?> saveFile(
          {String? dialogTitle,
          String? fileName,
          String? initialDirectory,
          i2.FileType? type,
          List<String>? allowedExtensions,
          i6.Uint8List? bytes,
          bool? lockParentWindow}) =>
      (super.noSuchMethod(
          Invocation.method(#saveFile, [], {
            #dialogTitle: dialogTitle,
            #fileName: fileName,
            #initialDirectory: initialDirectory,
            #type: type,
            #allowedExtensions: allowedExtensions,
            #bytes: bytes,
            #lockParentWindow: lockParentWindow
          }),
          returnValue:
              i3.Future<String?>.value()) as i3.Future<String?>);
  @override
  i3.Future<bool?> clearTemporaryFiles() =>
      (super.noSuchMethod(Invocation.method(#clearTemporaryFiles, []),
          returnValue: i3.Future<bool?>.value()) as i3.Future<bool?>);
  @override
  i3.Future<String?> getDirectoryPath(
          {String? dialogTitle,
          bool? lockParentWindow,
          String? initialDirectory,
          String? restorationId}) =>
      (super.noSuchMethod(
          Invocation.method(#getDirectoryPath, [], {
            #dialogTitle: dialogTitle,
            #lockParentWindow: lockParentWindow,
            #initialDirectory: initialDirectory,
            #restorationId: restorationId
          }),
          returnValue:
              i3.Future<String?>.value()) as i3.Future<String?>);
}