// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/providers/song_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/song.dart' as _i4;
import 'package:repertoire_coach/domain/repositories/song_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends _i1.Mock implements _i2.SongRepository {
  MockSongRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Song>> getSongsByConcert(String? concertId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSongsByConcert,
          [concertId],
        ),
        returnValue: _i3.Future<List<_i4.Song>>.value(<_i4.Song>[]),
      ) as _i3.Future<List<_i4.Song>>);

  @override
  _i3.Future<_i4.Song?> getSongById(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #getSongById,
          [songId],
        ),
        returnValue: _i3.Future<_i4.Song?>.value(),
      ) as _i3.Future<_i4.Song?>);

  @override
  _i3.Future<void> createSong(_i4.Song? song) => (super.noSuchMethod(
        Invocation.method(
          #createSong,
          [song],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> updateSong(_i4.Song? song) => (super.noSuchMethod(
        Invocation.method(
          #updateSong,
          [song],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSong,
          [songId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
