// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:mockito/mockito.dart' as i1;
import 'package:repertoire_coach/domain/entities/song.dart' as i5;
import 'package:repertoire_coach/domain/repositories/song_repository.dart'
    as i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends i1.Mock implements i3.SongRepository {
  MockSongRepository() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<List<i5.Song>> getSongsByConcert(String? concertId) =>
      (super.noSuchMethod(Invocation.method(#getSongsByConcert, [concertId]),
              returnValue: i4.Future.value(<i5.Song>[]))
          as i4.Future<List<i5.Song>>);
  @override
  i4.Future<i5.Song?> getSongById(String? songId) =>
      (super.noSuchMethod(Invocation.method(#getSongById, [songId]),
              returnValue: i4.Future.value(i5.Song(id: '', concertId: '', title: '', createdAt: DateTime.now(), updatedAt: DateTime.now())))
          as i4.Future<i5.Song?>);
  @override
  i4.Future<void> createSong(i5.Song? song) =>
      (super.noSuchMethod(Invocation.method(#createSong, [song]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
  @override
  i4.Future<bool> updateSong(i5.Song? song) =>
      (super.noSuchMethod(Invocation.method(#updateSong, [song]),
          returnValue: i4.Future.value(false)) as i4.Future<bool>);
  @override
  i4.Future<void> deleteSong(String? songId) =>
      (super.noSuchMethod(Invocation.method(#deleteSong, [songId]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
}