// Mocks generated by Mockito 5.0.17.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:mockito/mockito.dart' as i1;
import 'package:repertoire_coach/domain/entities/track.dart' as i5;
import 'package:repertoire_coach/domain/repositories/track_repository.dart'
    as i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [TrackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackRepository extends i1.Mock implements i3.TrackRepository {
  MockTrackRepository() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<List<i5.Track>> getTracksBySong(String? songId) =>
      (super.noSuchMethod(Invocation.method(#getTracksBySong, [songId]),
              returnValue: i4.Future.value(<i5.Track>[]))
          as i4.Future<List<i5.Track>>);
  @override
  i4.Future<i5.Track?> getTrackById(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#getTrackById, [trackId]),
              returnValue: i4.Future.value(i5.Track(id: '', songId: '', name: '', createdAt: DateTime.now(), updatedAt: DateTime.now())))
          as i4.Future<i5.Track?>);
  @override
  i4.Future<void> createTrack(i5.Track? track) =>
      (super.noSuchMethod(Invocation.method(#createTrack, [track]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
  @override
  i4.Future<bool> updateTrack(i5.Track? track) =>
      (super.noSuchMethod(Invocation.method(#updateTrack, [track]),
          returnValue: i4.Future.value(false)) as i4.Future<bool>);
  @override
  i4.Future<void> deleteTrack(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#deleteTrack, [trackId]),
          returnValue: i4.Future.value(null),
          returnValueForMissingStub: i4.Future.value()) as i4.Future<void>);
}