// Mocks generated by Mockito 5.4.6 from annotations
// in repertoire_coach/test/presentation/widgets/loop_control_buttons_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repertoire_coach/domain/entities/marker.dart' as _i4;
import 'package:repertoire_coach/presentation/providers/loop_control_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoopControls].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoopControls extends _i1.Mock implements _i2.LoopControls {
  MockLoopControls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLooping => (super.noSuchMethod(
        Invocation.getter(#isLooping),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> setLoopFromMarkers(
    _i4.Marker? startMarker,
    _i4.Marker? endMarker,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLoopFromMarkers,
          [
            startMarker,
            endMarker,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setLoopFromMarkerToPosition({
    required _i4.Marker? marker,
    required Duration? customPosition,
    required bool? markerIsStart,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLoopFromMarkerToPosition,
          [],
          {
            #marker: marker,
            #customPosition: customPosition,
            #markerIsStart: markerIsStart,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setCustomLoop({
    required Duration? startPosition,
    required Duration? endPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomLoop,
          [],
          {
            #startPosition: startPosition,
            #endPosition: endPosition,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearLoop() => (super.noSuchMethod(
        Invocation.method(
          #clearLoop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
